<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture"
    nsURI="http:///ArchitectureMetaModel.ecore" nsPrefix="br.pucrio.inf.les.genarch.models.architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Architecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//ArchitectureContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourcesContainer" upperBound="-1"
        eType="#//ArchitectureResourcesContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragmentsContainer" upperBound="-1"
        eType="#//ArchitectureFragmentContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ArchitectureComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureResourcesContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="#//ArchitectureFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFragmentContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fragments" upperBound="-1"
        eType="#//ArchitectureFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dependences" upperBound="-1"
        eType="#//ArchitectureEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReverseDependences" upperBound="-1"
        eType="#//ArchitectureEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureComponent" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ArchitectureClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" upperBound="-1"
        eType="#//ArchitectureAspect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
        eType="#//ArchitectureComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureClass" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MethodRef" upperBound="-1"
        eType="#//ArchitectureMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AttributeRef" upperBound="-1"
        eType="#//ArchitectureAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureAspect" eSuperTypes="#//ArchitectureEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFile" eSuperTypes="#//ArchitectureEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureTemplate" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFolder" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFolders" upperBound="-1"
        eType="#//ArchitectureFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFragment" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureMethod" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MethodDeclaration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ArchitectureCodePieceRef"
        upperBound="-1" eType="#//ArchitectureCodePiece" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureAttribute" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AttributDeclaration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureCodePiece" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ArchitectureCodePieceRef"
        upperBound="-1" eType="#//ArchitectureCodePiece" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
