<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecture"
    nsURI="http:///ArchitectureMetaModel.ecore" nsPrefix="br.pucrio.inf.les.genarch.models.architecture">
  <eClassifiers xsi:type="ecore:EClass" name="Architecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//ArchitectureContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourcesContainer" upperBound="-1"
        eType="#//ArchitectureResourcesContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ArchitectureComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureResourcesContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" upperBound="-1"
        eType="#//ArchitectureFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureComponent" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ArchitectureClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" upperBound="-1"
        eType="#//ArchitectureAspect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subComponents" upperBound="-1"
        eType="#//ArchitectureComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureClass" eSuperTypes="#//ArchitectureEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureAspect" eSuperTypes="#//ArchitectureEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFile" eSuperTypes="#//ArchitectureEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureTemplate" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureFolder" eSuperTypes="#//ArchitectureEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFolders" upperBound="-1"
        eType="#//ArchitectureFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//ArchitectureFile" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//ArchitectureTemplate" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
